<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LE15-GNK1-IND" failures="1" tests="7" name="Car loan" time="0.101" errors="0" timestamp="2022-02-11T15:11:14 IST">
  <testcase classname="testpackage.class3" name="Mobilelogincarloan" time="0.013"/>
  <testcase classname="testpackage.class3" name="Mobilesignincarloan" time="0.005"/>
  <testcase classname="testpackage.class3" name="Mobilesignoutcarloan" time="0.002"/>
  <testcase classname="testpackage.class3" name="Mobilesignoutcarloan" time="0.002"/>
  <testcase classname="testpackage.class3" name="Mobilesignoutcarloan" time="0.003"/>
  <testcase classname="testpackage.class3" name="Weblogincarloan" time="0.001"/>
  <testcase classname="testpackage.class3" name="failuretest" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testpackage.class3.failuretest(class3.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- failuretest -->
  <testcase classname="testpackage.class3" name="APIcarloan" time="0.0">
    <ignored/>
  </testcase> <!-- APIcarloan -->
</testsuite> <!-- Car loan -->
